services:
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379

  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

  flask_app:
    build: .
    container_name: flask_app
    ports:
      - 5000:5000
    environment:
      - REDIS_URI=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  redis_volume_data:
  redis_insight_volume_data: